# Theme Check Configuration for CI/CD
# https://shopify.dev/docs/themes/tools/theme-check/configuration

# Ignore certain files/directories
ignore:
  - node_modules/**
  - .git/**
  - .github/**
  - backup-*/**

# Only fail on critical errors for CI/CD
RequiredDirectories:
  enabled: true
  severity: error
  
RequiredFiles:
  enabled: true
  severity: error

SyntaxError:
  enabled: true
  severity: error

# Set translation issues to warnings instead of errors
MatchingTranslations:
  enabled: true
  severity: warning

MissingTranslations:
  enabled: true
  severity: warning

# Set undefined object warnings to info level
UndefinedObject:
  enabled: true
  severity: info

# Keep important security and structure checks as errors
ValidJson:
  enabled: true
  severity: error

LiquidTag:
  enabled: true
  severity: error

# Set block ID issues to warnings
UniqueStaticBlockId:
  enabled: true
  severity: warning

# Performance checks as warnings
AssetSizeCSS:
  enabled: true
  threshold_in_bytes: 150000
  severity: warning

AssetSizeJavaScript:
  enabled: true  
  threshold_in_bytes: 100000
  severity: warning

# Other checks as warnings
UnusedDocParam:
  enabled: true
  severity: warning

ParserBlockingJavaScript:
  enabled: true
  severity: warning

HtmlParsingError:
  enabled: true
  severity: error